"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Loader2, Package } from "lucide-react";
import { auth } from "@/lib/firebase";
type Order={id:string;orderNumber?:string;orderStatus?:string;paymentStatus?:string;totalPrice?:number;createdAt?:unknown};
const labels:Record<string,string>={pending_payment:"รอชำระเงิน",waiting_payment:"รอชำระเงิน",paid:"ชำระเงินแล้ว",queued:"เข้าคิวผลิต",printing:"กำลังผลิต",quality_check:"ตรวจคุณภาพ",ready:"พร้อมส่ง",shipping:"กำลังจัดส่ง",completed:"เสร็จสิ้น",cancelled:"ยกเลิก"};
function date(value:unknown){if(!value)return"—";const parsed=typeof value==="object"&&value&&"_seconds"in value?new Date(Number((value as{_seconds:number})._seconds)*1000):new Date(String(value));return Number.isNaN(parsed.getTime())?"—":parsed.toLocaleDateString("th-TH");}
export default function Customer3DOrdersPage(){const[orders,setOrders]=useState<Order[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");useEffect(()=>{const run=async()=>{const user=auth.currentUser;if(!user)return;const response=await fetch("/api/3d/orders",{headers:{Authorization:`Bearer ${await user.getIdToken()}`},cache:"no-store"});const data=await response.json();if(!response.ok)setError("ไม่สามารถโหลดรายการ Order ได้");else setOrders(Array.isArray(data.orders)?data.orders:[]);setLoading(false);};void run();},[]);return <main className="min-h-screen bg-[#f7f7fa] px-4 py-7 sm:px-8"><div className="mx-auto max-w-5xl"><Link href="/account/3d-printing" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/>กลับงาน 3D ของฉัน</Link><div className="mt-6 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-pink-500">KOKO 3D PRINTING</p><h1 className="mt-2 text-3xl font-black">คำสั่งซื้อของฉัน</h1></div></div>{error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-600">{error}</p>}{loading?<div className="mt-8 flex justify-center"><Loader2 className="animate-spin text-pink-500"/></div>:!orders.length?<div className="mt-8 rounded-3xl bg-white p-10 text-center text-slate-500 shadow-sm"><Package className="mx-auto text-slate-300" size={42}/><p className="mt-4">ยังไม่มีคำสั่งซื้อ 3D</p></div>:<div className="mt-8 grid gap-4">{orders.map(order=><Link key={order.id} href={`/account/3d-printing/orders/${order.id}`} className="rounded-3xl bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-lg font-black">#{order.orderNumber||order.id}</p><p className="mt-1 text-xs text-slate-400">{date(order.createdAt)}</p></div><span className="rounded-full bg-pink-50 px-3 py-1.5 text-xs font-bold text-pink-600">{labels[String(order.orderStatus)]||order.orderStatus}</span></div><div className="mt-5 flex items-end justify-between"><div><p className="text-xs text-slate-400">ยอดรวม</p><p className="mt-1 text-xl font-black">฿{Number(order.totalPrice||0).toLocaleString("th-TH")}</p></div><span className="inline-flex items-center gap-1 text-sm font-bold text-pink-500">ดูรายละเอียด<ArrowRight size={16}/></span></div></Link>)}</div>}</div></main>}
